###Get all products
http://127.0.0.1:8000/api/products/

###Get one product
http://127.0.0.1:8000/api/products/synergistic-systemic-implementation

### Nuevo Producto
POST http://127.0.0.1:8000/api/products/
content-type: application/json

{
    "name" : "Hamburger",
    "description" : "lorem weiuhiuwhediuww wiuedhwuid",
    "price" : "100.00",
    "total_quantity" : 10,
    "stock" : 10,
    "status" : true
}

### Edit product
PUT http://127.0.0.1:8000/api/products/hamburger
content-type: application/json

{
    "name" : "Hamburger 2",
    "description" : "lorem weiuhiuwhediuww wiuedhwuid 2",
    "price" : "100.00",
    "total_quantity" : 10,
    "stock" : 10,
    "status" : true
}

###Get one product
DELETE http://127.0.0.1:8000/api/products/hamburger-2

###Get all users
http://127.0.0.1:8000/api/users/

###Get one user
http://127.0.0.1:8000/api/users/irbing-alejandro-moreno-garcia

### New user
POST http://127.0.0.1:8000/api/users/
content-type: application/json

{
    "name" : "Irbing Alejandro Moreno Garcia",
    "email" : "irbing.moreno@outlook.com",
    "password" : "SuperPassword"
}
### New user
PUT http://127.0.0.1:8000/api/users/irbing-alejandro-moreno-garcia
content-type: application/json

{
    "name" : "irbing moreno olmos",
    "email" : "irbing.moreno@outlook.com",
    "password" : "SuperPassword"
}


###Delelte user
DELETE http://127.0.0.1:8000/api/users/irbing-moreno-olmos
